/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.23
 * Generated at: 2021-08-13 08:49:08 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class registrationPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\r\n");
      out.write(".logo {\r\n");
      out.write("\tposition : absolute;\r\n");
      out.write("\tmargin-top: 85px; \r\n");
      out.write("\tmargin-left: 85px; \r\n");
      out.write("\ttop : 0;\r\n");
      out.write("\tleft : 0;\r\n");
      out.write("}\t\t\r\n");
      out.write("\r\n");
      out.write("ul {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 100%;\r\n");
      out.write("    padding: 0;\r\n");
      out.write("    margin-top: 2px;\r\n");
      out.write("\tmargin-left: 85px;\r\n");
      out.write("    list-style-type: none;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cd {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 20%;\r\n");
      out.write("    text-decoration: none;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("    color: white;\r\n");
      out.write("    background-color: black;\r\n");
      out.write("    padding: 0.2em 0.6em;\r\n");
      out.write("    border-right: 1px solid white;\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write(".header {\r\n");
      out.write("\t  width : 100%;\r\n");
      out.write("\t  height : 150px;\r\n");
      out.write("\t  background-color : #2848BF;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".footer{\r\n");
      out.write("\t  width : 100%;\r\n");
      out.write("\t  height : 100px;\r\n");
      out.write("\t  background-color : #2D3656 ;\r\n");
      out.write("}\t\t\r\n");
      out.write("\r\n");
      out.write("div{\r\n");
      out.write("\tbackground-color: #e0ebeb;\r\n");
      out.write("    height: auto;\r\n");
      out.write("}\r\n");
      out.write("\t\t\r\n");
      out.write("input[type=text], input[type=password],input[type=Number],input[type=date] {\r\n");
      out.write("    width: 30%;\r\n");
      out.write("    padding: 12px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    height:10px;\r\n");
      out.write("    display: inline-block;\r\n");
      out.write("    border: 1px solid #ccc;\r\n");
      out.write("    box-sizing: border-box;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("button {\r\n");
      out.write("    background-color: #4CAF50;\r\n");
      out.write("    color: white;\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    margin: 8px 0;\r\n");
      out.write("    border: none;\r\n");
      out.write("    cursor: pointer;\r\n");
      out.write("    width: 25%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".cancelbtn {\r\n");
      out.write("    padding: 14px 20px;\r\n");
      out.write("    background-color: #f44336;\r\n");
      out.write("    width=25%;\r\n");
      out.write("}\r\n");
      out.write("body{\r\n");
      out.write("    background-color:#5072C6;\r\n");
      out.write("\tfont-family: Helvetica, sans-serif;\r\n");
      out.write("    padding: 5%;\r\n");
      out.write("}\r\n");
      out.write("\t\r\n");
      out.write(".cancelbtn,.signupbtn {\r\n");
      out.write("    float: left;\r\n");
      out.write("    width: 22%;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".container {\r\n");
      out.write("\twidth:auto;\r\n");
      out.write("    padding: 16px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".clearfix::after {\r\n");
      out.write("    content: \"\";\r\n");
      out.write("    clear: both;\r\n");
      out.write("    display: table;\r\n");
      out.write("    height:30px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("@media screen and (max-width: 300px) {\r\n");
      out.write("    .cancelbtn, .signupbtn {\r\n");
      out.write("       width: 100%;\r\n");
      out.write("    }\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("label{\r\n");
      out.write("\tmin-width:180px;\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t<script type=\"text/javascript\" src=\"js/Validation.js\"></script> \r\n");
      out.write("\t</head>\r\n");
      out.write("\t<body style =\"background:linear-gradient(135deg, #71b7e6, #9b59b6)\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t<img class = \"logo\" src = \"images/Logo.jpg\" height = \"110px\" width = \"auto\" border = 2%;>\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("\t<div class = \"header\">\r\n");
      out.write("        <FONT SIZE=\"4\" FACE=\"Algerian\" COLOR=\"white\"><CENTER><h1>Prestige Institute of Engineering,<br> Management & Research<br> Mumbai</h1><CENTER></FONT>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t\t<FONT FACE=\"arial\" COLOR=\"#00008B\"> <CENTER><h2>Permanently Affilated to University of Mumbai</h2>\r\n");
      out.write("\t\t\t\t<font size = \"3\" color = \"black\" >   Appooved By AICTE , Accredited by NBA<br>\r\n");
      out.write("\t\t\t\t\t<font size = \"2\" >(Recognized by UGC under the sections 2(f) and 12(B) of the UGC act 1956)</font>\r\n");
      out.write("\t\t\t\t</font>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t\t</CENTER>\r\n");
      out.write("\t\t</FONT>\r\n");
      out.write("\t\t\t    \r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<hr style = \"border-top: 2px solid black;\">\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t            <MARQUEE BEHAVIOUR=\"SLIDE\"><BIG><b><a href = \"registrationPage.jsp\" target = \"blank\"> Admissions open for year 2021-2022! Click here for registration. </a></b></BIG>  </MARQUEE>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<ul class = \"ul\">\r\n");
      out.write("\t\t\t\t<li><a class=\"cd\" href=\"index.jsp\">Home</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"cd\" href=\"About Us.html\">About us</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"cd\" href=\"registrationPage.jsp\">Registration Page</a></li>\r\n");
      out.write("\t\t\t\t<li><a class=\"cd\" href=\"Contact Details.html\">Contact us</a></li>\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\t<br>\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t<title>Registration Page</title>\r\n");
      out.write("\t\t\t<div style = \"text-align:center\">\r\n");
      out.write("\t\t\t\t<h2>Register for Admission</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<form name = \"frm\" action = \"action/registrationProcess.jsp\" method=\"POST\" style=\"border:1px solid #ccc\">\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t<legend>Personal details</legend>\r\n");
      out.write("\t\t\t\t\t<label><b>Name  </b> </label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Enter name\" name=\"sname\"  id=\"sname\" required>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>Father's Name</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Enter Name\" name=\"fname\"  id=\"fname\" required>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>Mother's Name</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Enter Name\" name=\"mname\"  id=\"mname\" required>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>Age of Student</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"Number\" placeholder=\"Enter Age\" name=\"age\" id=\"age\" required>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>Select Gender</b></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"gender\">\r\n");
      out.write("\t\t\t\t\t<option default>Select Gender</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"M\">Male</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"F\">Female</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"O\">Others</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>Address</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" placeholder=\"Enter Your Address\" name=\"address\" id=\"add\" required><br>\r\n");
      out.write("          </fieldset>\r\n");
      out.write("      \r\n");
      out.write("\t\t\t<fieldset>\r\n");
      out.write("\t\t\t\t\t<legend>Academic details</legend>\r\n");
      out.write("\t\t\t\t\t<label><b>Select Course</b></label>\r\n");
      out.write("\t\t\t\t\t<select name=\"coursename\" id=\"coursename\" onchange=\"checkFunt()\">\r\n");
      out.write("\t\t\t\t\t<option value=\"Def\">Select Course</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Computer Engineering\">Computer Engineering</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Civil Engineering\">Civil Engineering</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Mechanical Engineering\">Mechanical Engineering</option>\r\n");
      out.write("\t\t\t\t\t<option value=\"Electrical Engineering\">Electrical Engineering</option>\r\n");
      out.write("\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>10th Marks</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"percentssc\" id=\"percentssc\" placeholder=\"Enter your SSC percentage\" required>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>12th Marks</b></label>\r\n");
      out.write("                    <input type=\"text\" name=\"percenthsc\" id=\"percenthsc\" placeholder=\"Enter your HSC percentage\" required>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<label><b>Registration Fee</b></label>\r\n");
      out.write("\t\t\t\t\t<input type=\"Number\" placeholder=\"Fee Amount\" name=\"fee\" id = \"fee\"><br>\r\n");
      out.write("\t\t\t</fieldset>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t<input type=\"checkbox\" >\r\n");
      out.write("      \r\n");
      out.write("\t\t\t<p>I Agree to the <a href=\"file:///C:/Users/vikrant.gaikwad/Desktop/Project/Terms.pdf\">Terms & Condition</a>.</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"clearfix\">\r\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"signupbtn\" onclick = \"checkElig()\" value=\"Submit\" >Register</button>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</form>\r\n");
      out.write("\t\r\n");
      out.write("    <br>\r\n");
      out.write("\t\r\n");
      out.write("\t<div class = \"footer\">\r\n");
      out.write("    <footer>\r\n");
      out.write("\t\r\n");
      out.write("\t<br>\r\n");
      out.write("\t\r\n");
      out.write("        <p style = \"text-align:center\">\r\n");
      out.write("\t\t\t<font color = \"white\">@copyright Prestige Institute</font>\r\n");
      out.write("        </p>\r\n");
      out.write("\t\t\r\n");
      out.write("    </footer>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("    </body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
